- ### Maths calculation & plotting

1. numpy

**array**, **dtype**, **create array**

2. scipy

3. matplotlib

---

- ### numpy

In [ ]:
%% capture
%pip install numpy

**array / asarray**

In [84]:
import numpy as np

vec=np.array([1, 2, 3]) # using array to create a vector
print(vec)
print(vec.dtype,vec.ndim,vec.shape,vec.size,'\n') # data attributes

mat=np.asarray([(1, 2, 3), [4, 5, 6]]) # using asarray to avoid copying data
print(mat)
print(mat.dtype,mat.ndim,mat.shape,mat.size,'\n') # data attributes

mat[0, 1] = 10 # change value
print(mat,'\n')

m=mat.reshape(3, 2) # change shape without changing data
print(m,'\n')

m.shape= (2, 3) # change shape with changing data
print(m,'\n')

mtranspose = m.T # transpose
print(mtranspose)

[1 2 3]
int64 1 (3,) 3 

[[1 2 3]
 [4 5 6]]
int64 2 (2, 3) 6 

[[ 1 10  3]
 [ 4  5  6]] 

[[ 1 10]
 [ 3  4]
 [ 5  6]] 

[[ 1 10  3]
 [ 4  5  6]] 

[[ 1  4]
 [10  5]
 [ 3  6]]


In [67]:
arr=np.array([[1, 2], [3,4]],ndmin=2,dtype=complex) # dtype
print(arr)
print(arr.dtype,arr.ndim,arr.shape,arr.size,'\n') # data attributes
print(arr.real,'\n')
print(arr.imag) # real and imaginary parts

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128 2 (2, 2) 4 

[[1. 2.]
 [3. 4.]] 

[[0. 0.]
 [0. 0.]]


**create array**

In [102]:
series=np.arange(1, 10, 2) # array with step
print(series,'\n')

series2=np.linspace(0, 10, 6) # array with specified number of elements
print(series2,'\n')

series3=np.logspace(0, 4, 5) # logarithmically spaced array with default base 10
print(series3,'\n')

[1 3 5 7 9] 

[ 0.  2.  4.  6.  8. 10.] 

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04] 



In [97]:
a=np.empty((3, 3),dtype=int) # empty array
print(a,'\n')

b=np.zeros((2, 2),dtype=float) # zeros array
print(b,'\n')

c=np.ones((2),dtype=float) # ones array
print(c,'\n')

d=np.zeros_like(c) # zeros like shape of c
print(d,'\n')

e=np.ones_like(d) # ones like shape of d
print(e,'\n')

[[4607182418800017408 4611686018427387904 4613937818241073152]
 [4616189618054758400 4617315517961601024 4618441417868443648]
 [4619567317775286272 4620693217682128896 4621256167635550208]] 

[[0. 0.]
 [0. 0.]] 

[1. 1.] 

[0. 0.] 

[1. 1.] 



**dtype**

In [25]:
student=[('name', 'S20'), ('age', 'i4'), ('marks', 'f4')]
a = np.array([('abc', 21, 50),('xyz', 18, 75)],dtype=student) # structured array
print(a)
print(a.ndim)
print(a.shape)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
1
(2,)


**create array from buffer/iterator**

In [ ]:
import numpy as np

st=b'Hello World'
arr=np.frombuffer(st,dtype='S1') # from buffer
print(arr)

list=range(10)
iter=iter(list)
arr=np.fromiter(iter, dtype=float) # from iterator
print(arr)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


**slice**

In [114]:
import numpy as np

arr=np.arange(15).reshape(5,3) # from range
print(arr,'\n')

s=slice(0, 9, 2) # slice
print(arr[s],'\n')
print(arr[0:9:2],'\n') # same as above

arr[s] = 0 # change values using slice
print(arr,'\n')

print(arr[..., 1]) # ellipsis to select all rows and second column

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]] 

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]] 

[[ 0  0  0]
 [ 3  4  5]
 [ 0  0  0]
 [ 9 10 11]
 [ 0  0  0]] 

[ 0  4  0 10  0]
