- ### Numpy

1. [Array creation](#array-creation)

2. [Array attributes](#array-attributes)

3. [Array slicing](#array-slicing)

4. [Array broadcasting](#array-broadcasting)

5. [Array reshaping](#array-reshaping)

6. [Array manipulation](#Array-manipulation)

7. [Mathematical Functions](#mathematical-functions)

8. [Matrix and vector operation](#matrix-and-vector-operation)

---

- ### Array creation

In [ ]:
%%capture
%pip install numpy

**array / asarray**

In [ ]:
import numpy as np

vec=np.array([1, 2, 3]) # 1-dim array
print(vec)
print(vec.dtype,vec.ndim,vec.shape,vec.size,'\n') # data attributes

mat=np.asarray([(1, 2, 3), [4, 5, 6]]) # using asarray to avoid copying data
print(mat) # mixed types [] and () are converted to pure [] type
print(mat.dtype,mat.ndim,mat.shape,mat.size,'\n') # data attributes

[1 2 3]
int64 1 (3,) 3 

[[1 2 3]
 [4 5 6]]
int64 2 (2, 3) 6 



**arange**

In [2]:
import numpy as np

series=np.arange(1, 10, 2) # array with step
print(series,'\n')

series2=np.linspace(0, 10, 6) # array with specified number of elements
print(series2,'\n')

series3=np.logspace(0, 4, 5) # logarithmically spaced array with default base 10
print(series3,'\n')

[1 3 5 7 9] 

[ 0.  2.  4.  6.  8. 10.] 

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04] 



**empty/zeros/ones**

In [3]:
import numpy as np

a=np.empty((3, 3),dtype=int) # empty array
print(a,'\n')

b=np.zeros((2, 2),dtype=float) # zeros array
print(b,'\n')

c=np.ones((2),dtype=float) # ones array
print(c,'\n')

d=np.zeros_like(c) # zeros like shape of c
print(d,'\n')

e=np.ones_like(d) # ones like shape of d
print(e,'\n')

f=np.full((2, 2), 7) # full array with constant value
print(f,'\n')

[[0 0 0]
 [0 0 0]
 [0 0 0]] 

[[0. 0.]
 [0. 0.]] 

[1. 1.] 

[0. 0.] 

[1. 1.] 

[[7 7]
 [7 7]] 



**from buffer/iterator**

In [ ]:
import numpy as np

st=b'Hello World'
arr=np.frombuffer(st,dtype='S1') # from buffer
print(arr)

list=range(10)
iter=iter(list)
arr=np.fromiter(iter, dtype=float) # from iterator
print(arr)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


---

- ### Array attributes

**dtype/nidm/shape/size**

In [67]:
arr=np.array([[1, 2], [3,4]],ndmin=2,dtype=complex) # dtype
print(arr)
print(arr.dtype,arr.ndim,arr.shape,arr.size,'\n') # data attributes
print(arr.real,'\n')
print(arr.imag) # real and imaginary parts

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
complex128 2 (2, 2) 4 

[[1. 2.]
 [3. 4.]] 

[[0. 0.]
 [0. 0.]]


In [25]:
student=[('name', 'S20'), ('age', 'i4'), ('marks', 'f4')]
a = np.array([('abc', 21, 50),('xyz', 18, 75)],dtype=student) # structured array
print(a)
print(a.ndim)
print(a.shape)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
1
(2,)


---

- ### Array slicing

**slice**

In [114]:
import numpy as np

arr=np.arange(15).reshape(5,3) # from range
print(arr,'\n')

s=slice(0, 9, 2) # slice
print(arr[s],'\n')
print(arr[0:9:2],'\n') # same as above

arr[s] = 0 # change values using slice
print(arr,'\n')

print(arr[..., 1]) # ellipsis to select all rows and second column

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]] 

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]] 

[[ 0  0  0]
 [ 3  4  5]
 [ 0  0  0]
 [ 9 10 11]
 [ 0  0  0]] 

[ 0  4  0 10  0]


**indexing**

In [15]:
import numpy as np
arr=np.arange(15).reshape(5,3) # from range
print(arr,'\n')

rows=np.array([3,1]) # select specific rows
cols=np.array([2,1]) # select specific columns
x=arr[rows,cols]
print(x,'\n') 

y=arr[arr>8] # boolean indexing
print(y,'\n')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[11  4] 

[ 9 10 11 12 13 14] 



In [5]:
import numpy as np
arr=np.arange(15).reshape(5,3) # from range
print(arr,'\n')

rows=np.array([[1,2,3],[2,2,1]]) # rows index
cols=np.array([[0,1,0],[2,0,1]]) # columns index
x=arr[rows,cols]
print(x,'\n')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[3 7 9]
 [8 6 4]] 



In [5]:
import numpy as np
arr=np.arange(15).reshape(5,3) # from range
print(arr,'\n')
x=arr[1:4,[1,2]] # select specific rows and columns
y=arr[1:3,...]
z=arr[1:4:2,1:3] # select specific rows and columns with step
print(x,'\n')
print(y,'\n')
print(z,'\n')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[[ 4  5]
 [ 7  8]
 [10 11]] 

[[3 4 5]
 [6 7 8]] 

[[ 4  5]
 [10 11]] 



**filter**

In [33]:
import numpy as np
arr=np.array([1,2,np.nan,3,np.nan,5]) # array with NaN values
print(arr,'\n')
print(arr[~np.isnan(arr)],'\n') # remove NaN values, ~ is the bitwise NOT operator

a=np.array([1, 2, 3+4j])
print(a[np.iscomplex(a)],'\n') # remove complex numbers

[ 1.  2. nan  3. nan  5.] 

[1. 2. 3. 5.] 

[3.+4.j] 



In [11]:
import numpy as np
arr=np.arange(15).reshape(5,3) # from range
print(arr,'\n')
x=arr[[0,2,1,4],[1,2,2,0]] # select specific elements using lists
y=arr[[0,2,1,4]] # select specific rows using lists
print(x,'\n')
print(y,'\n') 


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

[ 1  8  5 12] 

[[ 0  1  2]
 [ 6  7  8]
 [ 3  4  5]
 [12 13 14]] 



---

- ### Array broadcasting

**broadcasting**

In [ ]:
import numpy as np
 
x = np.array([[1, 2]])
y = np.array([[4], [5]])  
b = np.broadcast(x, y) # broadcast x and y
print(b.shape) # shape of the broadcasted array
for x,y in b: # iterate over the broadcasted array
    print(x,y)

(2, 2)
1 4
2 4
1 5
2 5


In [ ]:
import numpy as np
 
x = np.array([[1, 2, 3]])
y = np.broadcast_to(x, (3, 3)) # broadcast x to shape (3, 3)
print(y,'\n') # broadcasted array

[[1 2 3]
 [1 2 3]
 [1 2 3]] 



**auto-broadcasting**

In [28]:
import numpy as np
arr1=np.array([1, 2, 3])
arr2= np.array([6, 7, 8])
arr3= np.array([[1, 2, 3], [4, 5, 6]]) # higher dim array
arr0=np.tile(arr1, (2, 1)) # tiling arr1 to create a 2D array

print(arr1 + arr2,'\n') # same shape, element-wise addition
print(arr1 + arr3,'\n') # broadcasting addition
print(arr0 + arr3,'\n') # tiling to the same shape, the same with broadcasting

print(arr1 * arr2,'\n') # element-wise multiplication
print(arr1 * arr3,'\n') # broadcasting multiplication
print(arr0 * arr3,'\n') # tiling to the same shape, the same with broadcasting

[ 7  9 11] 

[[2 4 6]
 [5 7 9]] 

[[2 4 6]
 [5 7 9]] 

[ 6 14 24] 

[[ 1  4  9]
 [ 4 10 18]] 

[[ 1  4  9]
 [ 4 10 18]] 



---

- ### Array reshaping

**nditerator**

In [1]:
import numpy as np
arr=np.arange(15).reshape(5,3) # from range
print(arr,'\n')
for x in np.nditer(arr): # iterate over elements in default order
    print(x, end=' ')
print('\n')
for x in np.nditer(arr.T): # iterate over transposed array
    print(x, end=' ')
print('\n')
for x in np.nditer(arr, order='F'): # iterate over elements in Fortran order
    print(x, end=' ')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] 

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 

0 3 6 9 12 1 4 7 10 13 2 5 8 11 14 

**reshape & resize**

In [9]:
import numpy as np
 
a = np.arange(0,60,5).reshape(3,4)
b = np.arange(0,60,20).reshape(3,1)
c = np.resize(a, (3, 8)) # resize a to the same shape as b
print(a,'\n')
print(a,'\n')
print(c,'\n')

for x, y in np.nditer([a, b]): # iterate over two arrays with broadcasting
    print(f"({x},{y})", end=' ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

[[ 0  5 10 15 20 25 30 35]
 [40 45 50 55  0  5 10 15]
 [20 25 30 35 40 45 50 55]] 

(0,0) (5,0) (10,0) (15,0) (20,20) (25,20) (30,20) (35,20) (40,40) (45,40) (50,40) (55,40) 

**flat &  flatten & ravel**

In [28]:
import numpy as np
a = np.arange(0,20,2).reshape(2,5)
b = a.flat
c = a.flatten() # flatten the array, copying needed

print(a,'\n')
print(b,'\n') # flat iterator
for x in b: # iterate over flat iterator
    print(x, end=' ')
print('\n')
print(c)

a=a.ravel() # ravel the array, no copying needed
print(a,'\n')

[[ 0  2  4  6  8]
 [10 12 14 16 18]] 


0 2 4 6 8 10 12 14 16 18 

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18] 



**transpose**

In [ ]:
import numpy as np

m = np.arange(1, 10).reshape(3, 3) # create a 3x3 matrix
print(m,'\n')

mt = m.T # transpose
print(mt,'\n')

np.transpose(m) # another way to transpose
print(np.transpose(m))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


---

- ### Array manipulation

**axis**

In [29]:
import numpy as np

a = np.arange(0,18,3).reshape(1,2,3) # create a 3x3x3 matrix
print(a,'\n')
print(a.shape,'\n')
e= np.where(a==15) # find elements equal to 10
print(e,'\n')

b = np.moveaxis(a,0,2) # shift axis 0 to axis 1
print(b,'\n')
print(b.shape,'\n')
f= np.where(b==15) # find elements equal to 10
print(f,'\n')

c = np.swapaxes(a,0,2) # swap axis 0 and axis 1
print(c,'\n')
print(c.shape,'\n')
g= np.where(c==15) # find elements equal to 10
print(g,'\n')

[[[ 0  3  6]
  [ 9 12 15]]] 

(1, 2, 3) 

(array([0]), array([1]), array([2])) 

[[[ 0]
  [ 3]
  [ 6]]

 [[ 9]
  [12]
  [15]]] 

(2, 3, 1) 

(array([1]), array([2]), array([0])) 

[[[ 0]
  [ 9]]

 [[ 3]
  [12]]

 [[ 6]
  [15]]] 

(3, 2, 1) 

(array([2]), array([1]), array([0])) 



**dimension**

In [15]:
import numpy as np
x = np.array([[1, 2, 3]])
y = np.expand_dims(x, axis=2) # add a new axis at the beginning
z = np.squeeze(y, axis=0) # remove the new axis
print(x.shape) # original shape
print(y.shape) # shape after adding a new axis
print(z.shape) # shape after removing the new axis
print('\n',x) # array after adding a new axis
print('\n',y) # array after adding a new axis
print('\n',z) # array after adding a new axis

(1, 3)
(1, 3, 1)
(3, 1)

 [[1 2 3]]

 [[[1]
  [2]
  [3]]]

 [[1]
 [2]
 [3]]


**merge**

In [19]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z = np.concatenate((x, y), axis=0) # concatenate along axis 0
w = np.concatenate((x, y), axis=1) # concatenate along axis 1
print(z,'\n') # concatenated array
print(w,'\n') # concatenated array
print(x.shape) # shape of x
print(y.shape) # shape of y
print(z.shape) # shape of z
print(w.shape) # shape of w

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] 

(2, 3)
(2, 3)
(4, 3)
(2, 6)


**stack**

In [7]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])
z =np.stack((x, y), axis=0) # stack along axis 0
w = np.stack((x, y), axis=1) # stack along axis 1
u = np.hstack((x, y)) # horizontal stack
v = np.vstack((x, y)) # vertical stack

print(x.shape) # shape of x
print(y.shape) # shape of y
print(z.shape) # shape of z
print(w.shape) # shape of w
print(u.shape) # shape of z
print(v.shape) # shape of w

print(z,'\n') # stacked array
print(w,'\n') # stacked array
print(u,'\n') # stacked array
print(v,'\n') # stacked array

(2, 3)
(2, 3)
(2, 2, 3)
(2, 2, 3)
(2, 6)
(4, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]] 

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 



**split**

In [26]:
import numpy as np
x = np.array([[1, 2], [4, 5]])
y = np.split(x, 2, axis=0) # split along axis 0
z = np.hsplit(x, 2) # split along axis 1
print(x.shape) # shape of x
print(y[0].shape) # shape of y
print(z[0].shape,'\n') # shape of z
print(y[0],'\n') # split array along axis 0
print(z[0],'\n') # split array along axis 1

(2, 2)
(1, 2)
(2, 1) 

[[1 2]] 

[[1]
 [4]] 



**append**

In [15]:
import numpy as np
x = np.array([[1, 2], [4, 5]])
y = np.array([[5, 6], [7, 8]])
z = np.append(x, y, axis=0) # append along axis 0
w = np.append(x, y, axis=1) # append along axis 1
u = np.append(x, [2,4])
print(z,'\n') # shape of x
print(w,'\n') # shape of y
print(u) # shape of z

[[1 2]
 [4 5]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [4 5 7 8]] 

[1 2 4 5 2 4]


**insert**

In [10]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array(5)
z = np.insert(x, 1, y, axis=0) # insert along axis 0 at index 1
w = np.insert(x, 1, y, axis=1) # insert along axis 1 at index 1
u = np.insert(x, 1, [9, 10]) # insert at index 1 without axis leads to flattening
print(z,'\n') # shape of x
print(w,'\n') # shape of y
print(u) # shape of z

[[1 2]
 [5 5]
 [3 4]] 

[[1 5 2]
 [3 5 4]] 

[ 1  9 10  2  3  4]


**delete**

In [13]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.delete(x, 1, axis=0) # delete along axis 0 at index 1
z = np.delete(x, 1, axis=1) # delete along axis 1 at index 1
u = np.delete(x, 3) # delete at index 1 without axis leads to flattening
print(y,'\n')
print(z,'\n')
print(u) # shape of z 

[[1 2]] 

[[1]
 [3]] 

[1 2 3]


**unique**

In [27]:
import numpy as np
x = np.array([1,2,3,3,9,4,1,5]) # create an array with duplicates
y = np.unique(x) # find unique elements
print(y,'\n') # unique elements
z, indices, counts = np.unique(x, return_index=True, return_counts=True) # find unique elements and their indices
print(indices,'\n') # indices of unique elements
print(x[indices],'\n') # original elements at unique indices
print(counts,'\n') # counts of unique elements

[1 2 3 4 5 9] 

[0 1 2 5 7 4] 

[1 2 3 4 5 9] 

[2 1 2 1 1 1] 



- ### Mathematical Functions

**elementary functions**

In [22]:
import numpy as np
x = np.array([0,np.pi/4,np.pi/3,np.pi]) # create an array
sin = np.sin(x) # sine of elements
cos = np.cos(x) # cosine of elements
tan = np.tan(x) # tangent of elements
print(np.around(sin, decimals=2),'\n') # sine values
print(np.around(cos, decimals=2),'\n') # cosine values
print(np.around(tan, decimals=2),'\n') # tangent value
print(np.tan(np.pi/2),'\n') # tangent of pi/2, should be inf

[0.   0.71 0.87 0.  ] 

[ 1.    0.71  0.5  -1.  ] 

[ 0.    1.    1.73 -0.  ] 

1.633123935319537e+16 



In [9]:
import numpy as np
x = np.array([0, 1/3, 1/2, 1]) # create an array
arcsin = np.arcsin(x) # arcsine of elements
arccos = np.arccos(x) # arccosine of elements
arctan = np.arctan(x) # arctangent of elements
print(np.around(arcsin, decimals=2),'\n') # arcsine values
print(np.floor(arccos),'\n') # arccosine values
print(np.ceil(arctan),'\n') # arctangent values

[0.   0.34 0.52 1.57] 

[1. 1. 1. 0.] 

[0. 1. 1. 1.] 



**elementary operator**

In [15]:
import numpy as np
a = np.array([[3, 4, 5, 6],[7, 8, 9, 10]])
b = np.array([12, 13, 14, 15])
c = np.add(a, b) # element-wise addition
d = np.subtract(a, b) # element-wise subtraction
e = np.multiply(a, b) # element-wise multiplication
f = np.divide(a, b) # element-wise division
print(c,'\n') # addition result
print(d,'\n') # subtraction result
print(e,'\n') # multiplication result
print(f,'\n') # division result

[[15 17 19 21]
 [19 21 23 25]] 

[[-9 -9 -9 -9]
 [-5 -5 -5 -5]] 

[[ 36  52  70  90]
 [ 84 104 126 150]] 

[[0.25       0.30769231 0.35714286 0.4       ]
 [0.58333333 0.61538462 0.64285714 0.66666667]] 



---

- ### Matrix and vector operation

**matrix multi and vector dot product**

In [3]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[11,12],[13,14]])
c=d=np.arange(8).reshape(2,2,2)

print(np.dot(a,b),'\n') # matrix and vector mixed product
print(np.matmul(a,b),'\n') # matrix multi
print(np.matmul(c,d),'\n') # matrix multi with 3d arrays
print(np.vdot(a,b),'\n') # flatten to vector dot product
print(np.inner(a,b),'\n') # component-wise inner product

[[37 40]
 [85 92]] 

[[37 40]
 [85 92]] 

[[[ 2  3]
  [ 6 11]]

 [[46 55]
  [66 79]]] 

130 

[[35 41]
 [81 95]] 



**linear algebra**


In [6]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[1],[2]])
det=np.linalg.det(a)
sol=np.linalg.solve(a,b)
print(np.around(det,2),'\n',)
print(sol,'\n')
print(np.dot(np.linalg.inv(a),b))

-2.0 

[[0. ]
 [0.5]] 

[[0. ]
 [0.5]]
